backend:
  name: github
  repo: durian-leader/durian-leader.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "分类", name: "categories", widget: "select", options: ["学术", "工作", "生活"]}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "正文", name: "body", widget: "markdown"}